global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'rag2-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['rag-app:8000']
        labels:
          service: 'rag-app'